name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      node-version: 12.x

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node-version }}

    - run: npm install

    - run: npm run test
